### ISSUE TITLE
Invalid HTTPS certs for software-carpentry.org and files.software-carpentry.org

### ISSUE THREAD

**Issue by wking** [swcarpentry/site#509]
We need working HTTPS for secure downloads of binary files (securing both the download itself and our published hashes for verifying the download, see swcarpentry/bc#488).  However, neither site currently has a cert with the right common name or one signed by an “official” CA:

    $ wget https://files.software-carpentry.org/SWCarpentryInstaller.exe
     --2014-05-20 09:10:38-- https://files.software-carpentry.org/SWCarpentryInstaller.exe
    Resolving files.software-carpentry.org... 174.136.14.108
    Connecting to files.software-carpentry.org|174.136.14.108|:443... connected.
    ERROR: cannot verify files.software-carpentry.org's certificate, issued by ‘/C=US/ST=Unknown/L=Unknown/O=Unknown/OU=Unknown/CN=vps1.sensibleadventures.com/emailAddress=ssl@vps1.sensibleadventures.com’:
      Self-signed certificate encountered.
        ERROR: certificate common name ‘vps1.sensibleadventures.com’ doesn't match requested host name ‘files.software-carpentry.org’.
    To connect to files.software-carpentry.org insecurely, use `--no-check-certificate'.

    $ wget https://software-carpentry.org/
    --2014-05-20 09:18:09-- https://software-carpentry.org/
    Resolving software-carpentry.org... 174.136.14.108
    Connecting to software-carpentry.org|174.136.14.108|:443... connected.
    ERROR: cannot verify software-carpentry.org's certificate, issued by ‘/C=US/ST=Unknown/L=Unknown/O=Unknown/OU=Unknown/CN=vps1.sensibleadventures.com/emailAddress=ssl@vps1.sensibleadventures.com’:
      Self-signed certificate encountered.
        ERROR: certificate common name ‘vps1.sensibleadventures.com’ doesn't match requested host name ‘software-carpentry.org’.
    To connect to software-carpentry.org insecurely, use `--no-check-certificate'.

**Comment by pipitone** [comment]
Fixed. Closing.

**Comment by wking** [comment]
On Mon, Jan 26, 2015 at 06:05:56PM -0800, Jon Pipitone wrote:
> Fixed. Closing.

It looks like you missed files.software-carpentry.org:

  $ wget https://files.software-carpentry.org/SWCarpentryInstaller.exe
  --2015-01-26 18:51:28--  https://files.software-carpentry.org/SWCarpentryInstaller.exe
  ERROR: Failed to open cert /etc/ssl/certs/README.RootCerts: (0).
  Resolving files.software-carpentry.org... 143.95.62.73
  Connecting to files.software-carpentry.org|143.95.62.73|:443... connected.
  GnuTLS: A TLS warning alert has been received.
  GnuTLS: received alert [112]: The server name sent was not recognized
  The certificate's owner does not match hostname ‘files.software-carpentry.org’

Hitting https://files.software-carpentry.org/ in Firefox gives me:

  files.software-carpentry.org uses an invalid security certificate.

  The certificate is only valid for the following names:
    software-carpentry.org , www.software-carpentry.org

  (Error code: ssl_error_bad_cert_domain)

**Comment by wking** [comment]
On Mon, Jan 26, 2015 at 06:50:13PM -0800, W. Trevor King wrote:
>   The certificate is only valid for the following names:
>     software-carpentry.org , www.software-carpentry.org

It's probably best to get a single cert for software-carpentry.org and
*.software-carpentry.org.  Then we don't have to get a new cert for
things like amy.software-carpentry.org.

**Comment by gvwilson** [comment]
@pipitone can you please have a look at our other domains?

**Comment by pipitone** [comment]
Bah.

**Comment by gvwilson** [comment]
@pipitone Can we now close this one?

**Comment by wking** [comment]
On Thu, Feb 05, 2015 at 11:03:52AM -0800, Jon Pipitone wrote:
> Closed #509.

Yay!  Thanks :).

**Comment by wking** [comment]
On Mon, Jan 26, 2015 at 06:50:13PM -0800, W. Trevor King wrote:

> Hitting https://files.software-carpentry.org/ in Firefox gives me:
> 
>   files.software-carpentry.org uses an invalid security certificate.
> 
>   The certificate is only valid for the following names:
>     software-carpentry.org , www.software-carpentry.org
> 
>   (Error code: ssl_error_bad_cert_domain)

I'm still seeing this today.  Did files.software-carpentry.org ever
get a valid certificate?

**Comment by gvwilson** [comment]
@jduckles @pipitone ?

**Comment by pbanaszkiewicz** [comment]
@wking:

We have two certificates, one for `software-carpentry.org` and one for `*.software-carpentry.org`.

`files.software-carpentry.org` was moved to a different machine long time ago by me and I didn't set up the cert on it. I fixed it now, but I somehow managed to broke `https://www.software-carpentry.org` (it's being served as `files.swc.org`) - working on it.

**Comment by pbanaszkiewicz** [comment]
The issue should now be fixed.
